import Vue from 'vue';
import Vuex from 'vuex';
import { months } from '@/common/utils';

Vue.use(Vuex);

export default new Vuex.Store({
    state: {
        isLoading: true,
        calendarSelected: 2,
        currentMonth: 8,
        colors: [
            ['#222121', '#29323C', '#485563'],
            ['#FF1F47', '#FF0844', '#FFB199'],
            ['#85878B', '#78787A', '#BDBBBE'],
            ['#3D4EB8', '#4250A7', '#6B7CE8'],
            ['#48B6AD', '#48BDB7', '#85D8D3'],
            ['#0C74D5', '#3780D7', '#45A6FF'],
            ['#FFA800', '#FDA085', '#F6D365'],
        ],
        user: {
            id: '463377',
        },
        first: {
            canBeDone: false,
            data: {
                name: 'ABC',
                icon: '😘',
                color: 2,
                days: [
                    2,
                    4,
                ],
                done: [],
            },
            days: [
                {
                    dow: 1,
                    d: 27,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 28,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 29,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 30,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 31,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 1,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 2,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 3,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 4,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 5,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 6,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 7,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 8,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 9,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 10,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 11,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 12,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 13,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 14,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 15,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 16,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 17,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 18,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 19,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 20,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 21,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 22,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 23,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 24,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 25,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 26,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 27,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 28,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 29,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 30,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 31,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 1,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'Checkpoint',
                },
                {
                    dow: 3,
                    d: 2,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 3,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 4,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 5,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 6,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 7,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 8,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 9,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 10,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 11,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 12,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 13,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 14,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 15,
                    m: 9,
                    y: 2020,
                    msD: 15,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 16,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 17,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 18,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 19,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 20,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 21,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 22,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 23,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 24,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 25,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 26,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 27,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 28,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 29,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 30,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 1,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 2,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 3,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 4,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 5,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 6,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 7,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 8,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 9,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 10,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 11,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 12,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 13,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 14,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 15,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 16,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 17,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 18,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 19,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 20,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 21,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 22,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 23,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 24,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 25,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 26,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 27,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 28,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 29,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 30,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 31,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
            ],
        },
        second: {
            canBeDone: true,
            data: {
                name: 'AAAABC',
                icon: '😘',
                color: 1,
                days: [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                ],
                done: [
                    {
                        d: 21,
                        m: 8,
                        y: 2020,
                        msD: 0,
                        type: 'Done',
                    },
                ],
            },
            days: [
                {
                    dow: 1,
                    d: 27,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 2,
                    d: 28,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 3,
                    d: 29,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 4,
                    d: 30,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 5,
                    d: 31,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 6,
                    d: 1,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 0,
                    d: 2,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 1,
                    d: 3,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 2,
                    d: 4,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 3,
                    d: 5,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 4,
                    d: 6,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 5,
                    d: 7,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 6,
                    d: 8,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 0,
                    d: 9,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 1,
                    d: 10,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 2,
                    d: 11,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 3,
                    d: 12,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 4,
                    d: 13,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 5,
                    d: 14,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 6,
                    d: 15,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 0,
                    d: 16,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 1,
                    d: 17,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 2,
                    d: 18,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 3,
                    d: 19,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 4,
                    d: 20,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 5,
                    d: 21,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Done',
                },
                {
                    dow: 6,
                    d: 22,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 0,
                    d: 23,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 1,
                    d: 24,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 2,
                    d: 25,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 3,
                    d: 26,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 4,
                    d: 27,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 5,
                    d: 28,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Break',
                },
                {
                    dow: 6,
                    d: 29,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'Checkpoint',
                },
                {
                    dow: 0,
                    d: 30,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 31,
                    m: 8,
                    y: 2020,
                    msD: 3,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 1,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 2,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 3,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 4,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 5,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 6,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 7,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 8,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 9,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 10,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 11,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 12,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 13,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 14,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 15,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 16,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 17,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 18,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 19,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 20,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 21,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 22,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 23,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 24,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 25,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 26,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 27,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 28,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 29,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 30,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 1,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 2,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 3,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 4,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 5,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 6,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 7,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 8,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 9,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 10,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 11,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 12,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 13,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 14,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 15,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 16,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 17,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 18,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 19,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 20,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 21,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 22,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 23,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 24,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 25,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 26,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 27,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 28,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 29,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 30,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 31,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 7,
                    d: 1,
                    m: 11,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
            ],
        },
        third: {
            canBeDone: false,
            data: {
                name: '',
                icon: '',
                color: 1,
                days: [],
                done: [],
            },
            days: [
                {
                    dow: 1,
                    d: 27,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 28,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 29,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 30,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 31,
                    m: 7,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 1,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 2,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 3,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 4,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 5,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 6,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 7,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 8,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 9,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 10,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 11,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 12,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 13,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 14,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 15,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 16,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 17,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 18,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 19,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 20,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 21,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 22,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 23,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 24,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 25,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 26,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 27,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 28,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 29,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 30,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 31,
                    m: 8,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 1,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 2,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 3,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 4,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 5,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 6,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 7,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 8,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 9,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 10,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 11,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 12,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 13,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 14,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 15,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 16,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 17,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 18,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 19,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 20,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 21,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 22,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 23,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 24,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 25,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 26,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 27,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 28,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 29,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 30,
                    m: 9,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 1,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 2,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 3,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 4,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 5,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 6,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 7,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 8,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 9,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 10,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 11,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 12,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 13,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 14,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 15,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 16,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 17,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 18,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 19,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 20,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 21,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 22,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 23,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 24,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 0,
                    d: 25,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 1,
                    d: 26,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 2,
                    d: 27,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 3,
                    d: 28,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 4,
                    d: 29,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 5,
                    d: 30,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
                {
                    dow: 6,
                    d: 31,
                    m: 10,
                    y: 2020,
                    msD: 0,
                    type: 'N',
                },
            ],
        },
    },
    getters: {
        calendar(state) {
            switch (state.calendarSelected) {
            case 1:
                return state.first;
            case 3:
                return state.third;
            default:
                return state.second;
            }
        },
        monthName(state) {
            return months[state.currentMonth - 1];
        },
    },
    mutations: {},
    actions: {},
});
